### PR TITLE
Use fixed seeds when generating random matrices in tests

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
We still have a non-determinism through `ReseedOnCloneRng`. Though it's interesting that these tests never failed before and now they do. I think I have to spend a little more time to see what is going on here. I guess that reseeding is not reliable on CI for some reason and the subquantizers are not different (enough). Rather than reseeding on clones, we should use splittable RNGs to generate RNGs for training subquantizers. I'll look a bit more into this later.

**Comment by danieldk** [comment]
Should be fixed now. If it passes CI now, this PR is ready for review.

**Comment by danieldk** [comment]
Seems like OpenBLAS + threading bites again? Even after removing non-determinisms in random number generation, CI was still failing (undeterministically). I looked at `openblas-src` builds the vendored BLAS and it seems to compile OpenBLAS without `USE_LOCKING`, which would explain the non-deterministic failures that we are encountering on CI.

This change switches CI to using MKL for tests and it hasn't failed so far.

Relevant upstream issue: https://github.com/blas-lapack-rs/openblas-src/issues/73

**Review by sebpuetz — APPROVED** [review]
Looks good to me

Do you think it's worth documenting the OpenBLAS issues somewhere more prominent than this PR?

**Comment by danieldk** [comment]
> Looks good to me
> 
> Do you think it's worth documenting the OpenBLAS issues somewhere more prominent than this PR?

We should, but probably in finalfusion-rust and finalfusion-utils, I wouldn't really expect users of reductive outside those crates.

**Comment by danieldk** [comment]
> > Looks good to me
> > Do you think it's worth documenting the OpenBLAS issues somewhere more prominent than this PR?
> 
> We should, but probably in finalfusion-rust and finalfusion-utils, I wouldn't really expect users of reductive outside those crates.

I should add that this would also be fine if the changes suggested in the upstream issue are adopted. Though SVD would probably be a lot slower without threading? Unfortunately, the best all-round answer to these issues seems to be: use MKL :(.

**Pull request merged**
